name: Build macOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    strategy:
      fail-fast: true
      matrix:
        os: [ macos-14, macos-15 ]
        config: [ Debug, Release ]

    runs-on: ${{matrix.os}}
    env:
      build-dir: build-${{matrix.os}}-${{matrix.config}}

    steps:
      - uses: actions/checkout@v4

      - name: Cache CMake dependencies
        uses: actions/cache@v4.2.4
        env:
          cache-name: cache-cmake-dependency-sources
        with:
          path: ${{github.workspace}}/${{env.build-dir}}/_deps/*-src
          key: ${{ env.cache-name }}-${{ hashFiles('**/CMakeLists.txt', 'CMake/**', 'Src/*.cmake') }}
          restore-keys: |
            ${{env.cache-name}}-

      - name: Cache CMake dependencies build objects
        uses: actions/cache@v4.2.4
        env:
          cache-name: cache-cmake-dependency-builds
        with:
          path: |
            ${{github.workspace}}/${{env.build-dir}}/_deps/*-build
            ${{github.workspace}}/${{env.build-dir}}/_deps/*-subbuild
          key: ${{env.cache-name}}-${{matrix.os}}-${{ hashFiles('**/CMakeLists.txt', 'CMake/**', 'Src/*.cmake') }}
          restore-keys: |
            ${{env.cache-name}}-${{matrix.os}}-${{matrix.config}}-

      - name: Configure CMake
        run: >
          cmake -B ${{env.build-dir}} -G Xcode -DCMAKE_BUILD_TYPE=${{ matrix.config }}
          -DCMAKE_OSX_ARCHITECTURES="arm64"
          -DCMAKE_XCODE_ATTRIBUTE_OSX_DEPLOYMENT_TARGET="13.5"
          -DCMAKE_XCODE_ATTRIBUTE_MACOSX_DEPLOYMENT_TARGET="13.5"
          -DCMAKE_XCODE_GENERATE_SCHEME=ON

      - name: Build CMake
        run: cmake --build ${{env.build-dir}} --parallel
