name: Build Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    strategy:
      fail-fast: true
      matrix:
        os: [ windows-latest ]
        config: [ Debug ]
        arch: [ x64 ]

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v4

      - name: Cache CMake dependencies
        uses: actions/cache@v4.2.4
        env:
          cache-name: cache-cmake-dependency-sources
        with:
          path: ${{github.workspace}}/build/_deps/*-src
          key: ${{ env.cache-name }}-${{ hashFiles('**/CMakeLists.txt', 'CMake/**', 'Src/*.cmake') }}
          restore-keys: |
            ${{ env.cache-name }}-

      - name: Cache CMake dependencies build objects
        uses: actions/cache@v4.2.4
        env:
          cache-name: cache-cmake-dependency-builds
        with:
          path: |
            ${{github.workspace}}/build/_deps/*-build
            ${{github.workspace}}/build/_deps/*-subbuild
          key: ${{env.cache-name}}-${{matrix.os}}-${{ hashFiles('**/CMakeLists.txt', 'CMake/**', 'Src/*.cmake') }}
          restore-keys: |
            ${{env.cache-name}}-${{matrix.os}}-

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -G "Visual Studio 17 2022" -A ${{matrix.arch}} -DCMAKE_BUILD_TYPE=${{ matrix.config }}

      - name: Build CMake
        run: cmake --build ${{github.workspace}}/build --parallel --config ${{matrix.config}}